language: python
python:
  - "2.7"
  - "3.7"

install: make

branches:
  only:
    - master

jobs:
  incude:
    - stage: test
      script:
        - make test
      python: '2.7'

    - stage: test
      script:
        - make test
      python: '2.7'
      env: DJANGO_VERSION=1.9

    - stage: test
      script:
        - make test
      python: '3.7'

    - stage: test
      script:
        - make test
      python: '3.7'
      env: DJANGO_VERSION=2.2

notifications:
  email:
    on_success: never
    on_failure: change
